default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "root_password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
　adapter: mysql2
　encoding: utf8
　pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
　database: <%= ENV['CONOHA_DB_NAME'] %>
　username: <%= ENV['CONOHA_DB_USERNAME'] %>
　password: <%= ENV['CONOHA_DB_PASSWORD'] %>
　host: <%= ENV['CONOHA_DB_HOSTNAME'] %>
　port: <%= ENV['CONOHA_DB_PORT'] %>
  url: <%= ENV['DATABASE_URL'] %>